<div class="menu-esquerda-conteudo">

    <div id="menu-lateral">
        <div>
            <h3><a href="#">Campos do formul&aacute;rio</a></h3>
            <div>
                <ul class="itens-form">
                    <li id="itens-form-titulo">
                        <span class="icone">
                            <img src="<?php echo $this->baseUrl() . '/images/icon/icone_titulo.png'; ?>" />
                        </span>
                        <span class="label">T&iacute;tulo Formul&aacute;rio</span>
                    </li>
                    <li id="itens-form-campo-text">
                        <span class="icone">
                            <img src="<?php echo $this->baseUrl() . '/images/icon/campo_text.png'; ?>" />
                        </span>
                        <span class="label">Input Text</span>
                    </li>
                    <li id="itens-form-campo-select">
                        <span class="icone ">
                            <img src="<?php echo $this->baseUrl() . '/images/icon/campo_select.png'; ?>" />
                        </span>
                        <span class="label">Select Box</span>
                    </li>
                    <li id="itens-form-campo-textarea">
                        <span class="icone ">
                            <img src="<?php echo $this->baseUrl() . '/images/icon/campo_textarea.png'; ?>" />
                        </span>
                        <span class="label">Textarea</span>
                    </li>
                    <li id="itens-form-campo-input-submit">
                        <span class="icone ">
                            <img src="<?php echo $this->baseUrl() . '/images/icon/campo_button.png'; ?>" />
                        </span>
                        <span class="label">Input Submit</span>
                    </li>

                </ul>
            </div>
        </div>
        <div>
            <h3><a href="#">Outros</a></h3>
            <div>
                <ul class="itens-form">
                    <li id="itens-form-campo-input-checkbox">
                        <span class="icone ">
                            <img src="<?php echo $this->baseUrl() . '/images/icon/campo_checkbox.png'; ?>" />
                        </span>
                        <span class="label">Input Checkbox</span>
                    </li>
                    <li id="itens-form-campo-input-radio">
                        <span class="icone ">
                            <img src="<?php echo $this->baseUrl() . '/images/icon/campo_radiobox.png'; ?>" />
                        </span>
                        <span class="label">Input Radio</span>
                    </li>
                    <li id="itens-form-campo-input-password">
                        <span class="icone ">
                            <img src="<?php echo $this->baseUrl() . '/images/icon/campo_password.png'; ?>" />
                        </span>
                        <span class="label">Input Password</span>
                    </li>
                    <li id="itens-form-campo-input-hidden">
                        <span class="icone ">
                            <img src="<?php echo $this->baseUrl() . '/images/icon/campo_hidden.png'; ?>" />
                        </span>
                        <span class="label">Input Hidden</span>
                    </li>
                    <li id="itens-form-caixa-texto">
                        <span class="icone">
                            <img src="<?php echo $this->baseUrl() . '/images/icon/caixa_texto.png'; ?>" />
                        </span>
                        <span class="label">Caixa de Texto</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>